### ISSUE TITLE
The webserver is offline

### ISSUE THREAD

**Issue by Sathish9** [wassermanlab/MANTA2#2]
How can I access the webserver?

**Comment by oriolfornes** [comment]
Dear user, unfortunately the MANTA2 server was build using old Perl CGI libraries.
These do not comply with current UBC IT security standards for which we have had to shut it down.
Still, you could install MANTA2 locally, data can be downloaded from [Zenodo](https://zenodo.org/record/1044747), and use the [search_manta2.py](https://github.com/wassermanlab/MANTA2/blob/master/manta2/manta2/scripts/search_manta2.py) script on your local installation.
